[profile.default]
solc = "0.8.23"
src = 'src'
out = 'dist/contracts'
test = 'test'
libs = ['lib']

via_ir = true
optimizer_runs = 1000000
#eth-rpc-url = 'http://localhost:8545'

fs_permissions = [{ access = "read", path = "dist/contracts" }, { access = "read-write", path = ".forge-snapshots/" }]

extra_output = ['storageLayout']

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
